tables:
  - name: product
    sql: {{ load_sql('product') }}
    description: >
      This table represents the product dimension for the Product Portfolio
      Rationalization & Demand Stability Data Product. It provides product
      attributes required to evaluate demand consistency, customer adoption,
      pricing effectiveness, and portfolio optimization decisions.
    public: true

    dimensions:
      - name: product_id
        type: string
        column: product_id
        description: "Unique identifier for each product."
        primary_key: true
        public: true

      - name: product_category
        type: string
        column: product_category
        description: "Product category used to analyze category-level demand stability."

      - name: product_name
        type: string
        column: product_name
        description: "Human-readable name of the product."

      - name: price
        type: number
        column: price
        description: "Listed price of the product."

      - name: price_band
        type: string
        sql: >
          CASE
            WHEN {price} < 20 THEN 'Low Price'
            WHEN {price} BETWEEN 20 AND 50 THEN 'Mid Price'
            ELSE 'High Price'
          END
        description: "Derived price band used for portfolio mix and affordability analysis."

      - name: product_positioning
        type: string
        sql: >
          CASE
            WHEN {price} >= 50 THEN 'Premium'
            WHEN {price} BETWEEN 20 AND 49 THEN 'Value'
            ELSE 'Budget'
          END
        description: >
          Product positioning classification used to evaluate
          portfolio balance across premium, value, and budget products.

      - name: portfolio_group
        type: string
        sql: >
          CASE
            WHEN {price} >= 50 THEN 'High Margin Portfolio'
            ELSE 'Volume Driven Portfolio'
          END
        description: >
          High-level portfolio grouping to support margin vs volume
          driven product analysis.

    measures:
      - name: total_products
        sql: "{product_id}"
        type: count_distinct
        description: "Total number of distinct products in the portfolio."

      - name: average_product_price
        sql: "AVG({price})"
        type: number
        description: "Average price of products within the portfolio."

      - name: premium_product_count
        sql: "CASE WHEN {price} >= 50 THEN {product_id} END"
        type: count_distinct
        description: "Number of premium-priced products in the portfolio."

      - name: budget_product_count
        sql: "CASE WHEN {price} < 20 THEN {product_id} END"
        type: count_distinct
        description: "Number of budget-priced products in the portfolio."

    segments:
      - name: premium_products
        sql: "{price} >= 50"
        description: "Products positioned in the premium price segment."

      - name: value_products
        sql: "{price} BETWEEN 20 AND 49"
        description: "Products positioned in the value segment."

      - name: budget_products
        sql: "{price} < 20"
        description: "Products positioned in the budget segment."
